### ISSUE TITLE
LOCATION ISSUE 

### ISSUE THREAD

**Issue by guys1444** [rynobax/indeed-scraper#1]
when setting location to diffrent country like israel there is no resuslts 

   query: 'Software',
    city: 'jerusalem,',   <<<<<
    radius: '25',
    level: 'entry_level',
    jobType: 'fulltime',
    maxAge: '7',
    sort: 'date',
    limit: '50'

**Comment by rynobax** [comment]
I just tried this and got one result, so it seems to be working now
