### ISSUE TITLE
No Jobs that being fetched.

### ISSUE THREAD

**Issue by jackwander** [rynobax/indeed-scraper#21]
Sometimes i can get a job but most of the time there is no return from the query.

**Comment by DGrothe-PhD** [comment]
Same for me

**Comment by jackwander** [comment]
@DGrothe-PhD there's a only a time limit where we can fetch a jobs coz after some multiple requests indeed will ask a captcha.

**Comment by bryon-czoch** [comment]
Works for me (pointing the code at a static copy that represents identical DOM structure :p), you're probably being rate limited.  Try using a proxy like https://levelup.gitconnected.com/anonymous-web-scrapping-with-node-js-tor-apify-and-cheerio-3b36ec6a45dc or add timeouts to the code so it just doesn't slam the site and trigger rate limiting.
