### ISSUE TITLE
Works only once

### ISSUE THREAD

**Issue by OliCKan** [rynobax/indeed-scraper#26]
It scraped on the first try, and when I run it again it returns an empty array every time now.
I even tried copying the example code, still returns an empty array.

**Comment by OliCKan** [comment]
Today I was able to run it about 3 or 4 times before it started returning an empty array.
I think Indeed starts blocking requests at some point.

**Comment by OliCKan** [comment]
Also I just realized it scrapes only the first 1000 jobs or so even if I no limit has been set, and even if I see thousands of results when I manually search Indeed with the same filters.
Maybe Indeed allows only ~1000 requests and then blocks them?

**Comment by thoratpratik** [comment]
faced same issue . it srapes only first time after that it gives empty array

**Comment by chris-aeviator** [comment]
this seems like you are running into a anti-scraping/captcha measure
