### ISSUE TITLE
Scraper Not working?

### ISSUE THREAD

**Issue by jeverd** [rynobax/indeed-scraper#5]
I am trying to use the scraper, however im not getting any jobs, it was working like a week ago tho, any ideas?

**Comment by ryantrellis** [comment]
Indeed changes something about the way the page was organized.  I published up a new version (3.0.0) which should work.

**Comment by rynobax** [comment]
Indeed changes something about the way the page was organized. I published up a new version (3.0.0) which should work.

**Comment by liaocanada** [comment]
The URLs are all showing up as 'https://www.indeed.comundefined'
