### ISSUE TITLE
Undefined URLs

### ISSUE THREAD

**Issue by liaocanada** [rynobax/indeed-scraper#8]
I'm using the new version (3.0.0). With the README input, all of the URLs are showing up as:

'https://www.indeed.comundefined'

**Comment by rynobax** [comment]
I believe #7 should have fixed that issue.  I released version 3.0.1, could you see if that version works for you?

**Comment by liaocanada** [comment]
Thanks for the reply, 3.0.1 works!

However, some of the URLs are ads, for example

'https://www.indeed.com/pagead/clk?mo=r&ad=-6NYlbfkN0DqLbVJflEmoNbAUZVjnTU_9JSbW8xb4TrI5dTQduRR7PnZvVZE7lkJ6gwbJW5s_67A8USTtOsdz3Kip_F2dH5Z0XDJYwCBrEKUskSH41tUtPdWbi8aR3hi2kzA2LtUQZTKG_FYuRFc9-kJGR8PkA_n4PBBbNwbM1I-778Mpkq7QL8VokCHtENvQRLoA1CoOEqLtM2lMjie5s6TAi5YoNzkTdE6hOdSyB32c6Er8vv8zECrUWvRWHZVqZy6BKu--x4npUf_una7oc8dFgtpxMZOlg_-3ceDRDH2ZSAMmnblLMX_eoUc7Wz07KAqnw-5H0hDiIdq22c1b_qHuCfoXSbHBGefqIgCSOEXLB3v-BCRZnsHSTCsLaN_lO--hAYzy8HFSJdTQR58ki3hosEQhrPYE85WrTxSDaQe-7Ua1evh4ieP0PquXUGo&vjs=3&p=3&fvj=1'

They all start with indeed.com/pagead/...
